version: "3.7"
services:
  web:
    build:
      context: ./docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    ports:
      - 8080:80
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    volumes:
      - .:/var/www/html
      - ./docker/vim/.vimrc:/home/user/.vimrc
      - ./docker/zsh/.zshrc:/home/user/.zshrc
      - ./docker/apache/sites:/etc/apache2/sites-enabled
      - ./docker/apache/php.ini:/usr/local/etc/php/conf.d/30-custom.ini
      - ./docker/supervisor/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf

    networks:
      - mynetwork
    depends_on:
      - db
      - maildev
      - redis
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "my-username"
      MYSQL_PASSWORD: "my-password"
      MYSQL_ROOT_PASSWORD: "my-root-password"
    ports:
      - "3316:3306"
    expose:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - mynetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8181:80"
    restart: always
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    networks:
      - mynetwork
  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"
    networks:
      - mynetwork
  redis:
    image: redis:5.0.5-stretch
    ports:
      - "6389:6379"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db-data:
    driver: local
